import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { Button, Form, Input, InputGroup } from "react-daisyui";
import { useForm } from "react-hook-form";
import { useRouter } from "next/router";
import { atom } from "jotai";
import { useAtom } from "jotai";
import { useEffect } from "react";

export const userIdAtom = atom("");

type RegisterForm = {
  name: string;
  contactInfo: string;
};

const Home: NextPage = () => {
  const createUser = trpc.useMutation("users.createUser");
  const router = useRouter();
  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm<RegisterForm>();
  const [, setUserId] = useAtom(userIdAtom);
  // const deleteDB = trpc.useQuery(["users.deleteUsers"]);

  const onSubmit = async (data: RegisterForm) => {
    const user = await createUser.mutateAsync(data);
    setUserId(user.id);

    router.push("/waiting");
  };

  return (
    <>
      <Head>
        <title>Speed Dating</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <Form className="w-1/3" onSubmit={handleSubmit(onSubmit)}>
          <Form.Label className="w-full" title="Name"></Form.Label>
          <Input
            {...register("name", { required: true })}
            type="text"
            placeholder="your name..."
            bordered
          />
          {errors.name && (
            <span className="text-red-600"> Name is required</span>
          )}

          <Form.Label className="w-full" title="Contact Info..."></Form.Label>
          <Input
            {...register("contactInfo", { required: true })}
            type="text"
            placeholder="phone number, social's, etc.."
            bordered
          />
          {errors.contactInfo && (
            <span className="text-red-600">Provide contact info</span>
          )}

          <Button className="mt-3" color="primary" type="submit">
            Join Room
          </Button>
        </Form>
      </main>
    </>
  );
};

export default Home;
